/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : COM0.c
**     Project   : testcom
**     Processor : MC9S12XET256MAA
**     Component : AsynchroSerial
**     Version   : Component 02.494, Driver 01.22, CPU db: 3.00.033
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2022/3/18, 11:05
**     Abstract  :
**         This component "AsynchroSerial" implements an asynchronous serial
**         communication. The component supports different settings of
**         parity, word width, stop-bit and communication speed,
**         user can select interrupt or polling handler.
**         Communication speed can be changed also in runtime.
**         The component requires one on-chip asynchronous serial channel.
**     Settings  :
**         Serial channel              : SCI1
**
**         Protocol
**             Init baud rate          : 19200baud
**             Width                   : 8 bits
**             Stop bits               : 1
**             Parity                  : none
**             Breaks                  : Disabled
**             Input buffer size       : 0
**             Output buffer size      : 0
**
**         Registers
**             Input buffer            : SCI1DRL   [$00D7]
**             Output buffer           : SCI1DRL   [$00D7]
**             Control register        : SCI1CR1   [$00D2]
**             Mode register           : SCI1CR2   [$00D3]
**             Baud setting reg.       : SCI1BD    [$00D0]
**             Special register        : SCI1SR1   [$00D4]
**
**             Priority                : 
**
**             Priority                : 
**
**         Used pins:
**         ----------------------------------------------------------
**           Function | On package           |    Name
**         ----------------------------------------------------------
**            Input   |     65               |  PS2_RxD1
**            Output  |     66               |  PS3_TxD1
**         ----------------------------------------------------------
**
**
**
**     Contents  :
**         RecvChar        - byte COM0_RecvChar(COM0_TComData *Chr);
**         SendChar        - byte COM0_SendChar(COM0_TComData Chr);
**         GetCharsInRxBuf - word COM0_GetCharsInRxBuf(void);
**         GetCharsInTxBuf - word COM0_GetCharsInTxBuf(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE COM0. */

#pragma MESSAGE DISABLE C4002 /* WARNING C4002: Result not used is ignored */
#pragma MESSAGE DISABLE C4301 /* INFORMATION C4301: Inline expansion done for function call */

#include "COM0.h"
//#include "Interrupt.h"

#pragma DATA_SEG COM0_DATA             /* Select data segment "COM0_DATA" */
#pragma CODE_SEG COM0_CODE




/*
** ===================================================================
**     Method      :  COM0_RecvChar (component AsynchroSerial)
**
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). This method is enabled only if the receiver property
**         is enabled.
**         [Note:] Because the preferred method to handle error and
**         break exception in the interrupt mode is to use events
**         <OnError> and <OnBreak> the return value ERR_RXEMPTY has
**         higher priority than other error codes. As a consequence the
**         information about an exception in interrupt mode is returned
**         only if there is a valid character ready to be read.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to a received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RXEMPTY - No data in receiver
**                           ERR_BREAK - Break character is detected
**                           (only when the <Interrupt service> property
**                           is disabled and the <Break signal> property
**                           is enabled)
**                           ERR_COMMON - common error occurred (the
**                           <GetError> method can be used for error
**                           specification)
** ===================================================================
*/
/*
byte COM0_RecvChar(COM0_TComData *Chr)
{
  byte Result = ERR_OK;                /* Return error code 
  byte StatReg = SCI1SR1;              /* Read status register 

  if (StatReg & (SCI1SR1_OR_MASK|SCI1SR1_NF_MASK|SCI1SR1_FE_MASK|SCI1SR1_PF_MASK)) { /* Is any error flag set? 
    Result = ERR_COMMON;               /* If yes then set common error value 
  } else if ((StatReg & SCI1SR1_RDRF_MASK) == 0U) { /* Is the reciver empty and no error is set? 
    return ERR_RXEMPTY;                /* If yes then error 
  } else {
    /* Else branch due to MISRA compliance 
  }
  *Chr = SCI1DRL;                      /* Read data from the receiver 
  return Result;                       /* Return error code 
}
byte os_input(byte * str){
    byte i=0;
    byte j;
    for(;;){
      if(COM0_RecvChar(&j) == ERR_OK){
      str[i] = j;
      i++;
    }else{
      return ++i;
    }
    }
}*/
/*
** ===================================================================
**     Method      :  COM0_SendChar (component AsynchroSerial)
**
**     Description :
**         Sends one character to the channel. If the component is
**         temporarily disabled (Disable method) SendChar method only
**         stores data into an output buffer. In case of a zero output
**         buffer size, only one character can be stored. Enabling the
**         component (Enable method) starts the transmission of the
**         stored data. This method is available only if the
**         transmitter property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte COM0_SendChar(byte Chr)
{
  if(SCI1SR1_TDRE == 0U) {             /* Is the transmitter empty? */
    return 1;                 /* If no then error */
  }
  SCI1DRL = (byte)Chr;
  return 0;                       /* OK */
}

void os_printf(byte * str){
  byte i;
  for(i = 0;str[i] != 0x00;i++){
    if(COM0_SendChar(str[i]) == 1){
      i--;
    }
    while(!SCI1SR1_TDRE);
  }
  return;
}
/*
** ===================================================================
**     Method      :  COM0_GetCharsInRxBuf (component AsynchroSerial)
**
**     Description :
**         Returns the number of characters in the input buffer. This
**         method is available only if the receiver property is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the input
**                           buffer.
** ===================================================================
*/
/*
word COM0_GetCharsInRxBuf(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  COM0_GetCharsInTxBuf (component AsynchroSerial)
**
**     Description :
**         Returns the number of characters in the output buffer. This
**         method is available only if the transmitter property is
**         enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the output
**                           buffer.
** ===================================================================
*/
/*
word COM0_GetCharsInTxBuf(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  COM0_Init (component AsynchroSerial)
**
**     Description :
**         Initializes the associated peripheral(s) and internal 
**         variables of the component. The method is called automatically 
**         as a part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void COM0_Init(void)
{                     /* Reset flags */
  /* SCI1CR1: LOOPS=0,SCISWAI=0,RSRC=0,M=0,WAKE=0,ILT=0,PE=0,PT=0 */
  setReg8(SCI1CR1, 0x00U);              
  /* SCI1SR2: AMAP=1,??=0,??=0,TXPOL=0,RXPOL=0,BRK13=0,TXDIR=0,RAF=0 */
  setReg8(SCI1SR2, 0x80U);             /* Switch to the alternative register set */ 
  /* SCI1ASR1: RXEDGIF=1,??=0,??=0,??=0,??=0,BERRV=0,BERRIF=1,BKDIF=1 */
  setReg8(SCI1ASR1, 0x83U);            /* Clear alternative status flags */ 
  /* SCI1ACR1: RXEDGIE=0,??=0,??=0,??=0,??=0,??=0,BERRIE=0,BKDIE=0 */
  setReg8(SCI1ACR1, 0x00U);             
  /* SCI1ACR2: ??=0,??=0,??=0,??=0,??=0,BERRM1=0,BERRM0=0,BKDFE=0 */
  setReg8(SCI1ACR2, 0x00U);             
  /* SCI1SR2: AMAP=0,??=0,??=0,TXPOL=0,RXPOL=0,BRK13=0,TXDIR=0,RAF=0 */
  setReg8(SCI1SR2, 0x00U);             /* Switch to the normal register set */ 
  (void) SCI1SR1;                      /* Reset interrupt request flags */
  /* SCI1CR2: TIE=0,TCIE=0,RIE=0,ILIE=0,TE=0,RE=0,RWU=0,SBK=0 */
  SCI1CR2 = 0U;                        /* Disable error interrupts */
  SCI1BD = 0x68U;                      /* Set prescaler bits */
  SCI1CR2 |= (SCI1CR2_TE_MASK | SCI1CR2_RE_MASK ); /* Enable transmitter, Enable receiver, Enable receiver interrupt */
}







/* END COM0. */


/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
